import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'TRACKPRO Ultra-Slim Card',
    description: 'Ultra-slim tracking card that fits in your wallet. Track your valuables with precision GPS and long battery life.',
    price: 89.99,
    originalPrice: 119.99,
    images: ['/images/products/trackpro-card-black.jpg'],
    category: 'Tracking Devices',
    tags: ['ultra-slim', 'wallet', 'gps', 'tracking'],
    inStock: true,
    stockQuantity: 25,
    rating: 4.8,
    reviewCount: 342,
    variants: [
      { id: 'color', name: 'Color', value: 'Black', inStock: true },
      { id: 'color', name: 'Color', value: 'Blue', inStock: true },
    ],
  },
  {
    id: '2',
    name: 'TRACKPRO Smart Tag',
    description: 'Advanced smart tag with Bluetooth connectivity and motion detection. Perfect for keys, bags, and personal items.',
    price: 49.99,
    images: ['/placeholder.svg'],
    category: 'Tracking Devices',
    tags: ['bluetooth', 'smart', 'motion-detection'],
    inStock: true,
    stockQuantity: 18,
    rating: 4.6,
    reviewCount: 189,
    variants: [
      { id: 'color', name: 'Color', value: 'White', inStock: true },
      { id: 'color', name: 'Color', value: 'Black', inStock: true },
    ],
  },
  {
    id: '3',
    name: 'TRACKPRO Wireless Charger',
    description: 'Fast wireless charging pad designed specifically for TRACKPRO devices. 15W fast charging with LED indicators.',
    price: 34.99,
    originalPrice: 44.99,
    images: ['/placeholder.svg'],
    category: 'Accessories',
    tags: ['wireless', 'charger', 'fast-charging'],
    inStock: true,
    stockQuantity: 30,
    rating: 4.4,
    reviewCount: 156,
  },
  {
    id: '4',
    name: 'TRACKPRO Passport Cover',
    description: 'Premium leather passport cover with built-in tracking technology. Keep your passport safe and trackable.',
    price: 79.99,
    images: ['/placeholder.svg'],
    category: 'Travel',
    tags: ['passport', 'leather', 'travel', 'tracking'],
    inStock: true,
    stockQuantity: 12,
    rating: 4.7,
    reviewCount: 98,
    variants: [
      { id: 'color', name: 'Color', value: 'Brown', inStock: true },
      { id: 'color', name: 'Color', value: 'Black', inStock: true },
    ],
  },
  {
    id: '5',
    name: 'TRACKPRO Smart Lock',
    description: 'Smart lock with tracking capabilities. Monitor access and receive alerts when your lock is tampered with.',
    price: 199.99,
    originalPrice: 249.99,
    images: ['/placeholder.svg'],
    category: 'Security',
    tags: ['smart-lock', 'security', 'access-control'],
    inStock: true,
    stockQuantity: 8,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: '6',
    name: 'TRACKPRO Family Pack',
    description: 'Complete tracking solution for the whole family. Includes 4 tracking cards and 1 smart tag with premium app access.',
    price: 299.99,
    originalPrice: 399.99,
    images: ['/placeholder.svg'],
    category: 'Bundles',
    tags: ['family', 'bundle', 'complete-solution'],
    inStock: true,
    stockQuantity: 15,
    rating: 4.9,
    reviewCount: 234,
  },
];